productapp/urls.py
from django.urls import path

from . import views
app_name='productapp'
urlpatterns = [

    path('', views.index,name='index'),
    path('product/<int:product_id>/',views.detail,name='detail'),
    path('add/',views.add_product,name='add_product'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

productproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("productapp.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, 
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT) 

productapp/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    price=models.IntegerField()
    img=models.ImageField(upload_to='pics')

def __str__(self):
    return self.name

productapp/forms.py
from django import forms
from .models import Product
# create forms-
class ProductForm(forms.ModelForm):
    class Meta:
        model=Product
        fields=['name', 'desc','price','img']

productapp/views.py
from django.shortcuts import render, redirect

from .forms import ProductForm
from .models import Product
# # from django. http import HttpResponse

# Create your views here.
def index(request):
    product=Product.objects.all()
    context={
        'product_list':product
    }
    return render(request,'index.html', context)

def detail(request, product_id):
    product=Product.objects.get(id=product_id)
    return render(request,"detail.html",{'product':product})

def add_product(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc=request.POST.get('desc',)
        price=request.POST.get('price',)
        img=request.FILES['img']
        product=Product(name=name,desc=desc,price=price,img=img)
        product.save()
    return render(request, 'add.html')


def update(request, id):
    product=Product.objects.get(id=id)
    form=ProductForm(request.POST or None, request.FILES, instance=product)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form':form, 'product':product})


def delete(request, id):
    if request.method=='POST':
        product=Product.objects.get(id=id)
        product.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter the  product name"><br>
    <input type="text" name="desc" placeholder="Enter the description"><br>
    <input type="text" name="price" placeholder="Enter the product price"><br>
    <input type="file" name="img"><br>
    <input type="submit" ><br>
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="#">
      Online Fashion Stores
    </a>
  </nav>

{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you want to delete this product?
    <input type="submit">
</form>
    

templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{product.img.url}}"width="300" height="300">
        </div>
        <div class="col-md-6">
            <h4>{{product.name}}</h4>
            <h6>{{product.desc}}</h6>
            <h6>{{product.price}}</h6>

            <a class="btn btn-warning" href="{% url 'productapp:update' product.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'productapp:delete' product.id %}">Delete</a>
        </div>

    </div>
</div>

{% endblock %}

templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
    

templates/index.html
{% extends 'base.html' %}
   {% block body %}
   
   
   <div class="container">
       <div class="row">
           {% for i in product_list %}
           <div class="col-md-4">
               <div class="card" style="width: 18rem;">
                   <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="250px" height="250px;">
                   <div class="card-body">
                     <h5 class="card-title">{{i.name}}</h5>
                     <p class="card-text">{{i.desc}}</p>
                     <a href="{% url 'productapp:detail' i.id %}" class="btn btn-primary">Click Here</a>
                   </div>
                 </div>
           </div>
           {% endfor %}
       </div>
   </div>
      
{% endblock %}